[package]
name = "android-intent"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/concoct-rs/android-intent-rs"
license = "MIT"
description = "Android intent utilities"

[dependencies]
jni = { version = "0.20.0" }
ndk-context = "0.1.1"
